#!/usr/bin/env ruby
#require File.dirname(__FILE__) + '../../config/boot'
require File.expand_path('../../config/boot', __FILE__)
#require File.expand_path(__FILE__)+ '/../../config/boot'
require 'commands/server'
